## this file is used by local-render, and my differ from _config.yml
## because of github and/or local pandoc idiosyncrasies
title: Single RNA-seq data analysis with R LOCALLY RENDERED
description: HAHA
theme: jekyll-theme-leap-day
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
  - COPYING.md
  - CONTRIBUTING.md
